version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  back-build-test-and-docker:
    working_directory: ~/deliya.es/back  
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/deliya.es
      - setup_remote_docker
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test-reports
            - store_artifacts:
                path: test-report.html
                prefix: tests
            - store_artifacts:
                path: coverage
                prefix: coverage
            - store_test_results:
                path: test-report.html
            - run:
                name: docker-image
                command: |
                  APP_NAME=deliya-es-back
                  TAG=latest
                  docker build -t $APP_NAME:$TAG .
                  docker login --username=alvaro@basallo.es --password=$HEROKU_AUTH_TOKEN registry.heroku.com
                  docker tag $APP_NAME:$TAG registry.heroku.com/$APP_NAME
                  docker push registry.heroku.com/$APP_NAME
  front-build-test-and-docker:
    working_directory: ~/deliya.es/front  
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/deliya.es
      - setup_remote_docker
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test-reports
            - store_artifacts:
                path: test-report.html
                prefix: tests
            - store_artifacts:
                path: coverage
                prefix: coverage
            - store_test_results:
                path: test-report.html
            - run:
                name: docker-image
                command: |
                  APP_NAME=deliya-es-front
                  TAG=latest
                  docker build -t $APP_NAME:$TAG .
                  docker login --username=alvaro@basallo.es --password=$HEROKU_AUTH_TOKEN registry.heroku.com
                  docker tag $APP_NAME:$TAG registry.heroku.com/$APP_NAME
                  docker push registry.heroku.com/$APP_NAME
workflows:
    back-build-test-and-docker:
      jobs:
        - back-build-test-and-docker
        - front-build-test-and-docker
        
