version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install-and-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

workflows:
  install-and-test:
    jobs:
      - install-and-test
